name: SpechtLabs Static-Pages deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive # fetch Hugo themes
          fetch-depth: 0

      - name: Init submodules
        run: git submodule update --init --recursive

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Upload static site artifacts
        shell: bash
        run: |
          # Fetch GitHub OIDC token
          TOKEN=$(curl -sSfL -X POST \
            -H "Authorization: bearer $ACTIONS_RUNTIME_TOKEN" \
            -H "Accept: application/json; api-version=2.0" \
            "https://api.github.com/actions/oidc/token?audience=your-api" \
            | jq -r '.value')

          # Prepare curl arguments
          CURL_ARGS=()
          for file in dist/*; do
            [ -f "$file" ] || continue
            CURL_ARGS+=("-F" "files[]=@${file}")
          done

          # Upload to your REST API
          curl -X POST https://static-pages.sphinx-map.ts.net/upload \
            -H "Authorization: Bearer $TOKEN" \
            "${CURL_ARGS[@]}"
