name: SpechtLabs Static-Pages deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive # fetch Hugo themes
          fetch-depth: 0

      - name: Init submodules
        run: git submodule update --init --recursive

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - uses: SpechtLabs/StaticPages-Upload@main
        with:
          apiUrl: https://staticpages.cedi.dev
          dir: public/
